// This file is auto-generated by scripts/msgpack-gen.lua
// *** DO NOT EDIT ***

#include <stdint.h>
#include <stdlib.h>

#include "msgpack_rpc/common.h"
#include "msgpack_rpc/server_defs.h"
#include "msgpack_rpc/server_impl.h"
#include "api.h"


static const NeovimRPCError wrong_number_of_params_error = {
  .code = kNeovimRPCWrongNumOfParamsError,
  .name = "NeovimRPCWrongNumOfParamsError",
  .message = "Wrong number of parameters."
};

MSGPACK_RPC_DECLARE_EXPECTED_TYPE_ERROR(uint)
MSGPACK_RPC_DECLARE_EXPECTED_TYPE_ERROR(ulong)
MSGPACK_RPC_DECLARE_EXPECTED_TYPE_ERROR(raw)

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_push_keys)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(1)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(raw, 0)
  api_push_keys(p_0);
  free(p_0);
  MSGPACK_RPC_PACK_RES_RESULT_VOID(res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_command)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(1)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(raw, 0)
  api_command(p_0);
  free(p_0);
  MSGPACK_RPC_PACK_RES_RESULT_VOID(res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_eval)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(1)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(raw, 0)
  api_eval(p_0);
  free(p_0);
  MSGPACK_RPC_PACK_RES_RESULT_VOID(res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_bind_eval)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(1)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(raw, 0)
  uint32_t api_result = api_bind_eval(p_0);
  free(p_0);
  MSGPACK_RPC_PACK_RES_RESULT(uint, api_result, res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_list_runtime_paths)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(0)
  char** api_result = api_list_runtime_paths();
  MSGPACK_RPC_PACK_RES_RESULT(list, api_result, res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_list_buffers)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(0)
  char** api_result = api_list_buffers();
  MSGPACK_RPC_PACK_RES_RESULT(list, api_result, res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_list_windows)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(0)
  char** api_result = api_list_windows();
  MSGPACK_RPC_PACK_RES_RESULT(list, api_result, res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_list_tabpages)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(0)
  char** api_result = api_list_tabpages();
  MSGPACK_RPC_PACK_RES_RESULT(list, api_result, res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_get_current_line)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(0)
  char* api_result = api_get_current_line();
  MSGPACK_RPC_PACK_RES_RESULT(raw, api_result, res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_get_current_buffer)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(0)
  uint32_t api_result = api_get_current_buffer();
  MSGPACK_RPC_PACK_RES_RESULT(uint, api_result, res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_get_current_window)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(0)
  uint32_t api_result = api_get_current_window();
  MSGPACK_RPC_PACK_RES_RESULT(uint, api_result, res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_get_current_tabpage)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(0)
  uint32_t api_result = api_get_current_tabpage();
  MSGPACK_RPC_PACK_RES_RESULT(uint, api_result, res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_set_current_line)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(1)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(raw, 0)
  api_set_current_line(p_0);
  free(p_0);
  MSGPACK_RPC_PACK_RES_RESULT_VOID(res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_set_current_buffer)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(1)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(uint, 0)
  api_set_current_buffer(p_0);
  MSGPACK_RPC_PACK_RES_RESULT_VOID(res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_set_current_window)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(1)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(uint, 0)
  api_set_current_window(p_0);
  MSGPACK_RPC_PACK_RES_RESULT_VOID(res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_set_current_tabpage)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(1)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(uint, 0)
  api_set_current_tabpage(p_0);
  MSGPACK_RPC_PACK_RES_RESULT_VOID(res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_get_option)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(1)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(raw, 0)
  char* api_result = api_get_option(p_0);
  free(p_0);
  MSGPACK_RPC_PACK_RES_RESULT(raw, api_result, res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_set_option)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(2)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(raw, 0)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(raw, 1)
  api_set_option(p_0, p_1);
  free(p_0);
  free(p_1);
  MSGPACK_RPC_PACK_RES_RESULT_VOID(res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_out_write)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(1)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(raw, 0)
  api_out_write(p_0);
  free(p_0);
  MSGPACK_RPC_PACK_RES_RESULT_VOID(res)
}

MSGPACK_RPC_METHOD_HANDLER_SIGNATURE(api_err_write)
{
  MSGPACK_RPC_CHECK_PARAMS_LEN(1)
  MSGPACK_RPC_CHECK_AND_UNPACK_PARAM(raw, 0)
  api_err_write(p_0);
  free(p_0);
  MSGPACK_RPC_PACK_RES_RESULT_VOID(res)
}

MsgpackRPCMethodHandler msgpack_rpc_lookup_method_handler(
  const msgpack_object_raw *method)
{
  char *suffix = method->ptr + 4;
  uint32_t suffix_len = method->size - 4;

#define MSGPACK_RPC_METHOD_COMPARE_AND_RET(method_suffix)      \
  if (strncmp(suffix, "##method_suffix##", suffix_len) == 0) { \
    return _handle_api_##method_suffix;                        \
  }

  MSGPACK_RPC_METHOD_COMPARE_AND_RET(push_keys)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(command)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(eval)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(bind_eval)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(list_runtime_paths)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(list_buffers)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(list_windows)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(list_tabpages)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(get_current_line)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(get_current_buffer)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(get_current_window)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(get_current_tabpage)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(set_current_line)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(set_current_buffer)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(set_current_window)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(set_current_tabpage)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(get_option)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(set_option)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(out_write)
  MSGPACK_RPC_METHOD_COMPARE_AND_RET(err_write)
  return NULL;
}